### ISSUE TITLE
Throw error when user specifies 2 ports with same name

### ISSUE THREAD

**Issue by erikdanie** [sifive/duhportinf#12]
I got the following error when I had 2 ports with the same name (but different capitalization). A more intuitive error message would be helpful.

```pytb
Traceback (most recent call last):
  File "./node_modules/.bin/duh-portinf", line 16, in <module>
    duhportinf.main_portinf.main()
  File "./node_modules/duhportinf/pylib/duhportinf/main_portinf.py", line 213, in main
    i_bus_mappings = get_bus_matches(unassn_ports, bus_defs)
  File "./node_modules/duhportinf/pylib/duhportinf/main_portinf.py", line 145, in get_bus_matches
    bt = BundleTree(ports)
  File "./node_modules/duhportinf/pylib/duhportinf/_bundle.py", line 232, in __init__
    root.update(self._subtree_from_port(port))
  File "./node_modules/duhportinf/pylib/duhportinf/_bundle.py", line 192, in update
    child.update(ss_child)
  File "./node_modules/duhportinf/pylib/duhportinf/_bundle.py", line 188, in update
    assert self.port == None
AssertionError
```

**Comment by Ramlakshmi3733** [comment]
would you be able to give me a sample duh file?

**Comment by erikdanie** [comment]
It's been a while since I submitted this issue. All I remember was that I had 2 ports with exactly the same name but different capitalization (i.e. `port_a` and `Port_a`)
