### ISSUE TITLE
pip3 not found

### ISSUE THREAD

**Issue by derekpappas** [sifive/duhportinf#5]
```± |master ?:1 ✗| → npm i github:sifive/duh

> duhportinf@0.1.0 install /Users/depappas/demo-block/node_modules/duhportinf
> npm run -s gen-reqs && npm run -s install-pyreqs && pip3 install --target $PWD/pylib .

Traceback (most recent call last):
  File ".npm-install/gen-local-req.py", line 13, in <module>
    txt = subprocess.check_output(['pip3', 'list', '--format=freeze'])
  File "/Users/depappas/anaconda3/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/Users/depappas/anaconda3/lib/python3.6/subprocess.py", line 403, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Users/depappas/anaconda3/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/Users/depappas/anaconda3/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pip3': 'pip3'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! duhportinf@0.1.0 install: `npm run -s gen-reqs && npm run -s install-pyreqs && pip3 install --target $PWD/pylib .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the duhportinf@0.1.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/depappas/.npm/_logs/2019-02-27T22_29_43_543Z-debug.log
```

**Comment by drom** [comment]
Assuming that Python 3.5+ is installed
