### ISSUE TITLE
npm i duh@1.9.0 get errors "can't combine user with prefix, exec_prefix/home, or install_(plat)base"

### ISSUE THREAD

**Issue by davidmlw** [sifive/duhportinf#8]
when run demo-block, in this step "npm i duh@1.9.0"

```
> duhportinf@0.3.0 preinstall /home/ubuntu/work/workspace-repeat/node_modules/.staging/duhportinf-b1615713
> .npm-install/check-py.sh


> duhportinf@0.3.0 install /home/ubuntu/work/workspace-repeat/node_modules/duhportinf
> npm run -s gen-reqs && npm run -s install-pyreqs && pip3 install --target $PWD/pylib .

You must give at least one requirement to install (see "pip help install")
Processing /home/ubuntu/work/workspace-repeat/node_modules/duhportinf
Installing collected packages: duhportinf
  Running setup.py install for duhportinf ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-4vhang_2-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-sg5khp4z-record/install-record.txt --single-version-externally-managed --compile --user --prefix= --home=/tmp/tmp1ofu55x7:
    running install
    error: can't combine user with prefix, exec_prefix/home, or install_(plat)base

    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-4vhang_2-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-sg5khp4z-record/install-record.txt --single-version-externally-managed --compile --user --prefix= --home=/tmp/tmp1ofu55x7" failed with error code 1 in /tmp/pip-4vhang_2-build/
```

**Comment by reedafoster** [comment]
I'm running into a similar issue installing duhportinf on WSL
Linux kernel: 4.4.0-17763-Microsoft
python3 version: 3.6.8
pip3 version: 9.01
node version: v8.10.0

```
$ npm i duhportinf

> duhportinf@0.3.0 preinstall /home/reedf/node_modules/.staging/duhportinf-a6b56c8a
> .npm-install/check-py.sh


> duhportinf@0.3.0 install /home/reedf/node_modules/duhportinf
> npm run -s gen-reqs && npm run -s install-pyreqs && pip3 install --target $PWD/pylib .

Collecting json5>=0.6.1 (from -r local-pylib-requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/30/44/062543d4a6718f99d82e5ecf9140dbdee8a03122f2c34fbd0b0609891707/json5-0.8.5-py2.py3-none-any.whl
Collecting cvxopt>=1.2.2 (from -r local-pylib-requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/98/54/f54833cd7d76212353f852e6daeb2c1150a0337a0de0c201f9f084da9219/cvxopt-1.2.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy>=0.19.1 (from -r local-pylib-requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/72/4c/5f81e7264b0a7a8bd570810f48cd346ba36faedbd2ba255c873ad556de76/scipy-1.3.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting numpy>=1.13.3 (from -r local-pylib-requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/87/2d/e4656149cbadd3a8a0369fcd1a9c7d61cc7b87b3903b85389c70c989a696/numpy-1.16.4-cp36-cp36m-manylinux1_x86_64.whl
Collecting jsonref>=0.2 (from -r local-pylib-requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/07/92/f8e4ac824b14af77e613984e480fa818397c72d4141fc466decb26752749/jsonref-0.2-py3-none-any.whl
Installing collected packages: json5, cvxopt, numpy, scipy, jsonref
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 360, in run
    prefix=options.prefix_path,
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 784, in install
    **kwargs
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 851, in install
    self.move_wheel_files(self.source_dir, root=root, prefix=prefix)
  File "/usr/lib/python3/dist-packages/pip/req/req_install.py", line 1064, in move_wheel_files
    isolated=self.isolated,
  File "/usr/lib/python3/dist-packages/pip/wheel.py", line 247, in move_wheel_files
    prefix=prefix,
  File "/usr/lib/python3/dist-packages/pip/locations.py", line 153, in distutils_scheme
    i.finalize_options()
  File "/usr/lib/python3.6/distutils/command/install.py", line 274, in finalize_options
    raise DistutilsOptionError("can't combine user with prefix, "
distutils.errors.DistutilsOptionError: can't combine user with prefix, exec_prefix/home, or install_(plat)base
npm WARN enoent ENOENT: no such file or directory, open '/home/reedf/package.json'
npm WARN reedf No description
npm WARN reedf No repository field.
npm WARN reedf No README data
npm WARN reedf No license field.
npm ERR! Linux 4.4.0-17763-Microsoft
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i" "duhportinf"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! duhportinf@0.3.0 install: `npm run -s gen-reqs && npm run -s install-pyreqs && pip3 install --target $PWD/pylib .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the duhportinf@0.3.0 install script 'npm run -s gen-reqs && npm run -s install-pyreqs && pip3 install --target $PWD/pylib .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the duhportinf package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run -s gen-reqs && npm run -s install-pyreqs && pip3 install --target $PWD/pylib .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs duhportinf
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls duhportinf
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/reedf/duhinstall/npm-debug.log
```

**Comment by jackkoenig** [comment]
I believe this issue has to do with certain distribution's handling of python3. For example, in Ubuntu: https://github.com/pypa/pip/issues/3826

As a workaround, try installing python 3.6 yourself.

We do need to find a workaround to put in duhportinf though

**Comment by KingFrige** [comment]
Maybe you need update pip/pip3

`sudo pip install --upgrade pip`

[Why does pip -t not work on Ubuntu 15.04?](https://askubuntu.com/questions/619838/why-does-pip-t-not-work-on-ubuntu-15-04)
